<a href="https://colab.research.google.com/github/Viktoria-coder-prog/frontend-learning/blob/main/%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np

In [8]:
# Задача 1. Загрузите и ознакомьтесь с полученным набором данных.
pd.read_csv('/content/diabet.csv')

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,class
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,125.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,29.0,125.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,125.0,30.4,0.315,23,0

In [10]:
# информация по таблице
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pregnancies               768 non-null    int64
 1   glucose                   768 non-null    float64
 2   bloodpressure             768 non-null    float64
 3   skinthickness             768 non-null    float64
 4   insulin                   768 non-null    float64
 5   bmi                       768 non-null    float64
 6   diabetespedigreefunction  768 non-null    float64
 7   age                       768 non-null    int64
 8   class                     768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [15]:
# Задача 2. Вычислите основные статистики (минимум, максимум, среднее, дисперсию) для всех столбцов.
df.agg(['min','max','mean','var'])

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,class
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000
mean,3.845052,121.656250,72.386719,29.108073,140.671875,32.457464,0.471876,33.240885,0.348958
var,11.354056,926.489244,146.328741,77.285567,7462.033002,47.267706,0.109779,138.303046,0.227483

In [47]:
# Задача 3. У скольких женщин старше 50 лет обнаружен диабет?
fltr_1 = (
    (df['class'] == 1)
    &
    (df['age']>50)
)
print(fltr_1.sum())

38

In [36]:
# Задача 4. Найдите трех женщин с наибольшим числом беременностей.
df['pregnancies'].nlargest(3)

159    17
88     15
298    14
Name: pregnancies, dtype: int64

In [48]:
# Задача 5. Сколько женщин возраста между 30 и 40 успело родить 3 или более детей?
# не совсем корректно поставлен вопрос, т.к. не у всех беременностей следствием является рождение детей, но оставим так
flt_2 = (df['pregnancies']>=3) & (df['age'].between(30,40))
print(flt_2.sum())

142

In [53]:
# Задача 6. Нормальным кровяным давлением будем считать давление в диапазоне [80-89].
# У какого процента женщин давление нормальное?
flt_3 = df['bloodpressure'].between(80,89)
print(flt_3.mean()*100)

18.880208333333336

In [62]:
# Задача 7. Считается, что BMI >= 30 - это признак ожирения. У скольких женщин с признаками ожирения
# кровяное давление выше среднего?
above_mean = df['bloodpressure'] > df['bloodpressure'].mean()
bmi_flt = df['bmi']>=30
flt_4 = bmi_flt & above_mean
print(flt_4.sum())

251

In [65]:
# Задача 8. Сравните средние значения для признаков Glucose, BloodPressure, Insulin среди тех,
# у кого обнаружен диабет, и тех, у кого его нет.
df.groupby('class').agg(
    mean_glucose = ('glucose','mean'),
    mean_bloodpressure = ('bloodpressure','mean'),
    mean_insulin = ('insulin','mean')
)

       mean_glucose  mean_bloodpressure  mean_insulin
class
0        110.682000           70.920000    127.792000
1        142.130597           75.123134    164.701493

In [78]:
# Задача 9. Добавьте новый бинарный признак: wasPregnant ∈ {0,1} - была женщина беременна (1) или нет (0).
df["wasPregnant"] = (df["pregnancies"] > 0).astype(int)
df[["pregnancies", "wasPregnant"]].head(5)

   pregnancies  wasPregnant
0            6            1
1            1            1
2            8            1
3            1            1
4            0            0

In [77]:
# Задача 10. Сравните процент больных диабетом среди женщин, которые были беременны и не были.
print(df.groupby("wasPregnant")["class"].mean() * 100)

wasPregnant
0    34.234234
1    35.007610
Name: class, dtype: float64

In [82]:
# Задача 11. Добавьте новый категориальный признак bodyType на основе столбца BMI:
# BMI Categories: Underweight = <18.5; Normal weight = 18.5–24.9; Overweight = 25–29.9; Obesity = BMI of 30 or greater.
# Признак должен принимать значения Underweight, Normal weight, Overweight и Obesity.
ctgrs = [
    (df['bmi'] < 18.5),
    (df['bmi'] >= 18.5) & (df['bmi'] <= 24.9),
    (df['bmi'] >= 25) & (df['bmi'] <= 29.9),
    (df['bmi'] >= 30)
]

column = [
    "Underweight",
    "Normal weight",
    "Overweight",
    "Obesity"
]

df['bmi_categories'] = np.select(ctgrs, column, default="Unknown")
df[['bmi', 'bmi_categories']]

      bmi bmi_categories
0    33.6        Obesity
1    26.6     Overweight
2    23.3  Normal weight
3    28.1     Overweight
4    43.1        Obesity
..    ...            ...
763  32.9        Obesity
764  36.8        Obesity
765  26.2     Overweight
766  30.1        Obesity
767  30.4        Obesity

[768 rows x 2 columns]

In [83]:
# Задача 12. Будем считать "здоровыми" тех, у кого нормальный вес и кровяное давление.
# Какой процент "здоровых" женщин больны диабетом?
normal_weight = df['bmi'].between(18.5, 24.9)
normal_pressure = df['bloodpressure'].between(80, 89)
healthy_fltr = normal_weight & normal_pressure
diabetes_percent = df[healthy_fltr]['class'].mean() * 100
print(diabetes_percent)

10.0